
    <footer class="primary-footer">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <a class="footer-logo-icon" href="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">
                          <path d="M.03 256.34h256V.34H.03v256zm62.46-130.95h97.41c1.04-.07 2.07-.27 3.07-.59 1.49-.46 2.89-1.16 4.15-2.08 1.54-1.09 2.83-2.49 3.79-4.11 1.15-2 1.71-4.29 1.63-6.59.11-2.34-.38-4.68-1.45-6.77-.85-1.6-2.08-2.98-3.57-4.02-1.3-.91-2.75-1.57-4.29-1.94-1.14-.29-2.3-.46-3.48-.5H62.49V73.55H164.1c3.68.1 7.34.66 10.88 1.67 4.4 1.2 8.54 3.22 12.19 5.96 4.11 3.12 7.47 7.12 9.84 11.7 2.9 5.95 4.28 12.53 4.02 19.15.25 6.61-1.2 13.17-4.2 19.06-2.47 4.63-5.9 8.69-10.07 11.88-3.65 2.76-7.79 4.79-12.19 6.01-3.41.99-6.93 1.55-10.48 1.67h-76.4v39.96h-25.2v-65.22z"/>
                        </svg>
                    </a>
                </div>
                <div class="col-4 col-footer-info">
                    <p class="footer-info">
                        2019 Paltron | 
                        <a href=""><?php echo __("Impressum"); ?></a> | 
                        <a href=""><?php echo __("Datenschutz"); ?></a>
                    </p>
                </div>
                <div class="col-4 col-footer-social-icons">
                    <ul class="footer-social-icons">
                        <li><a href=""><ion-icon name="logo-facebook"></ion-icon></a></li>
                        <li><a href=""><ion-icon name="logo-twitter"></ion-icon></a></li>
                        <li><a href=""><ion-icon name="logo-xing"></ion-icon></a></li>
                        <li><a href=""><ion-icon name="logo-linkedin"></ion-icon></a></li>
                    </ul>
                </div>    
            </div>
        </div>
    </footer>
    <a href="#" class="btn btn-primary back-to-top" id="return-to-top" role="button">
        <img src="<?php echo $td.'images/back-to-top.svg'?>" alt="back to top">
    </a>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>
        <script src="https://unpkg.com/ionicons@4.2.4/dist/ionicons.js"></script>
        <script src="<?php echo $td ?>js/vendor/owl.carousel.min.js"></script>
        <script src="<?php echo $td ?>js/main.js"></script>
        <script src="<?php echo $td ?>js/myjs.js"></script>
    </body>
</html>