<section class="recent-news">
    <div class="news-list">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12 news-list-item">
                    <a href="#">
                        <div class="image">
                            <img src="<?php echo $td.'images/news/news3.jpg' ?>" alt="recent-news" >
                            <div class="overlay">
                            </div>
                            <span class="overlay-text">Read More</span>
                        </div>
                        <span class="date">17, Juli 2019</span>
                        <h6 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 news-list-item">
                    <a href="#">
                        <div class="image">
                            <img src="<?php echo $td.'images/news/news2.jpg' ?>" alt="recent-news" >
                            <div class="overlay">
                            </div>
                            <span class="overlay-text">Read More</span>
                        </div>
                        <span class="date">17, Juli 2019</span>
                        <h6 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 news-list-item">
                    <a href="#">
                        <div class="image">
                            <img src="<?php echo $td.'images/news/news3.jpg' ?>" alt="recent-news" >
                            <div class="overlay">
                            </div>
                            <span class="overlay-text">Read More</span>
                        </div>
                        <span class="date">17, Juli 2019</span>
                        <h6 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    </a>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-12 news-list-item">
                    <a href="#">
                        <div class="image">
                            <img src="<?php echo $td.'images/news/news2.jpg' ?>" alt="recent-news" >
                            <div class="overlay">
                            </div>
                            <span class="overlay-text">Read More</span>
                        </div>
                        <span class="date">17, Juli 2019</span>
                        <h6 class="title">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h6>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
