    <section class="testimonials" id="testimonials">
        <div class="container grid-lg">
            <div class="testimonials-carousel owl-carousel">
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12 testimonial-person">
                        <div class="wrapper">
                            <img class="testimonial-image" src="<?php echo $td.'images/Lee-Taylor.jpg'; ?>" alt="lee-taylor" >
                            <div class="testimonial-person-details">
                                <p class="name">Lee Taylor</p>
                                <p>Recruiting Manager, </p>
                                <p>Microsoft Germany</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 testimonial-body">
                        <p>"Aufgrund der Zusammenarbeit mit PALTRON ist es uns gelungen, zahlreiche Positionen zu besetzen, für die es extrem schwierig war, passendes Personal zu finden. Die Profile der Kandidaten wurden mit der Zeit immer besser, weil PALTRON sehr genau verstanden hat, wer wir sind und nach welchen Menschen wir suchen."</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12 testimonial-person">
                        <div class="wrapper">
                            <img class="testimonial-image" src="<?php echo $td.'images/Lee-Taylor.jpg'; ?>" alt="lee-taylor" >
                            <div class="testimonial-person-details">
                                <p class="name">Lee Taylor</p>
                                <p>Recruiting Manager, </p>
                                <p>Microsoft Germany</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 testimonial-body">
                        <p>"Aufgrund der Zusammenarbeit mit PALTRON ist es uns gelungen, zahlreiche Positionen zu besetzen, für die es extrem schwierig war, passendes Personal zu finden. Die Profile der Kandidaten wurden mit der Zeit immer besser, weil PALTRON sehr genau verstanden hat, wer wir sind und nach welchen Menschen wir suchen."</p>
                    </div>
                </div>
            </div>
        </div>
    </section>   
    