    <section class="testimonials" id="testimonials">
        <div class="container grid-lg">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12 testimonial-person">
                    <img class="testimonial-image" src="http://via.placeholder.com/120x120" alt="" >
                    <div class="testimonial-person-details">
                        <h6>Vielen Dank fur eine tolle Kooperation!</h6>
                        <h6 class="name">Lee Taylor</h6>
                        <h6>Recruiting Manager, Microsoft Germany</h6>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 testimonial-body">
                    <p>"Aufgrund der Zusammenarbeit mit PALTRON ist es uns gelungen, zahlreiche Positionen zu besetzen, für die es extrem schwierig war, passendes Personal zu finden. Die Profile der Kandidaten wurden mit der Zeit immer besser, weil PALTRON sehr genau verstanden hat, wer wir sind und nach welchen Menschen wir suchen."</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6 offset-lg-6 col-md-12 col-sm-12">
                    <div class="all_testimonial_wrapper">
                        <div class="all_testimonial_note">
                            "PALTRON hatte alle Suchen in kurzester Zeit erfolgreich beendet..."
                        </div>
                        <a href="" class="all_testimonial "><ion-icon ios="ios-arrow-forward" md="md-arrow-forward"></ion-icon></a>
                    </div>         
                </div>
            </div>
        </div>
    </section>   
    